"""
00_curate_subset.py
===================
전체 YOLO 데이터셋(8클래스)에서 저사양 환경에서도 학습 가능한
소규모 subset을 추출 (stratified by primary class).

저사양 GPU(예: GTX 1050 2GB)·제한된 RAM 환경에서 파이프라인을
end-to-end로 검증하기 위한 용도. 전체 학습은 서버에서 수행한다.

산출물:
  <dst>/{train,valid,test}/{images,labels}/ + data.yaml + subset_report.json

사용법:
    python scripts/00_curate_subset.py \
      --src D:/YOLO_data_v3 --dst data/subset \
      --train 300 --val 60 --test 60
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
from collections import Counter
from pathlib import Path

# data.yaml 8클래스
CLASS_NAMES = [
    "Crack_Crazing", "Crack_Longitudinal", "Crack_Transverse",
    "human", "manhole", "pothole", "sewer", "vehicle",
]
DAMAGE_CLASSES = {0, 1, 2, 5}  # 균열 3종 + 포트홀


def primary_class(label_path: Path) -> int | None:
    """라벨에서 가장 먼저 등장하는 파손 클래스(없으면 첫 클래스, 빈 라벨은 None)."""
    if not label_path.exists():
        return None
    classes = []
    for line in label_path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if parts:
            try:
                classes.append(int(parts[0]))
            except ValueError:
                continue
    if not classes:
        return None
    dmg = [c for c in classes if c in DAMAGE_CLASSES]
    return dmg[0] if dmg else classes[0]


def collect(src_split: Path) -> list[dict]:
    """한 split 폴더에서 (image, label, primary_class) 수집."""
    img_dir = src_split / "images"
    lbl_dir = src_split / "labels"
    out = []
    if not img_dir.exists():
        return out
    for img in img_dir.iterdir():
        if img.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
            continue
        lbl = lbl_dir / (img.stem + ".txt")
        pc = primary_class(lbl)
        if pc is None:
            continue
        out.append({"image": img, "label": lbl, "primary_class": pc})
    return out


def stratified_take(items: list[dict], n: int, seed: int = 42) -> list[dict]:
    """파손 클래스 우선 + 클래스 균등 비율로 n개 추출."""
    rng = random.Random(seed)
    by_class: dict[int, list[dict]] = {}
    for it in items:
        by_class.setdefault(it["primary_class"], []).append(it)
    for v in by_class.values():
        rng.shuffle(v)

    # 파손 클래스를 우선 배치
    order = sorted(by_class.keys(), key=lambda c: (c not in DAMAGE_CLASSES, c))
    picked: list[dict] = []
    idx = {c: 0 for c in by_class}
    # round-robin
    while len(picked) < n and any(idx[c] < len(by_class[c]) for c in order):
        for c in order:
            if len(picked) >= n:
                break
            if idx[c] < len(by_class[c]):
                picked.append(by_class[c][idx[c]])
                idx[c] += 1
    return picked[:n]


def copy_split(items: list[dict], dst_split: Path) -> dict:
    img_dst = dst_split / "images"
    lbl_dst = dst_split / "labels"
    img_dst.mkdir(parents=True, exist_ok=True)
    lbl_dst.mkdir(parents=True, exist_ok=True)
    counter = Counter()
    for it in items:
        shutil.copy2(it["image"], img_dst / it["image"].name)
        shutil.copy2(it["label"], lbl_dst / it["label"].name)
        counter[it["primary_class"]] += 1
    return {CLASS_NAMES[k]: counter[k] for k in sorted(counter)}


def write_data_yaml(dst: Path) -> None:
    lines = [
        "# Subset of D:/YOLO_data_v3 for low-resource training",
        "# Generated by 00_curate_subset.py",
        f"path: {dst.resolve().as_posix()}",
        "train: train/images",
        "val: valid/images",
        "test: test/images",
        "",
        "nc: 8",
        "names:",
    ]
    for i, name in enumerate(CLASS_NAMES):
        lines.append(f"  {i}: {name}")
    (dst / "data.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--src", required=True, help="원본 데이터셋 루트")
    parser.add_argument("--dst", default="data/subset")
    parser.add_argument("--train", type=int, default=300)
    parser.add_argument("--val", type=int, default=60)
    parser.add_argument("--test", type=int, default=60)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    src = Path(args.src)
    dst = Path(args.dst)
    if not src.exists():
        raise SystemExit(f"원본 경로 없음: {src}")

    # 원본 split 명: train/valid/test
    pools = {s: collect(src / s) for s in ("train", "valid", "test")}
    print("원본 후보:", {s: len(v) for s, v in pools.items()})

    targets = {"train": args.train, "valid": args.val, "test": args.test}
    report = {"src": str(src), "dst": str(dst.resolve()), "splits": {}}

    for split, n in targets.items():
        pool = pools.get(split) or []
        # 부족하면 train 풀에서 보충
        if len(pool) < n and split != "train":
            pool = pool + pools["train"]
        picked = stratified_take(pool, n, seed=args.seed)
        by_class = copy_split(picked, dst / split)
        report["splits"][split] = {"count": len(picked), "by_class": by_class}
        print(f"  {split}: {len(picked)}장 {by_class}")

    write_data_yaml(dst)
    (dst / "subset_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\n[OK] subset 생성 → {dst}")
    print(f"  data.yaml: {dst / 'data.yaml'}")


if __name__ == "__main__":
    main()
